from fastapi import FastAPI, Query
import subprocess

app = FastAPI()

@app.get("/execute")
def execute_command(command: str = Query(..., description="Shell command generated by LLM")):
    try:
        output = subprocess.check_output(command, shell=True, text=True, stderr=subprocess.STDOUT)
        return {"output": output}
    except subprocess.CalledProcessError as e:
        return {"error": e.output or str(e)}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)

